### ISSUE TITLE
Mac App version support for C++ migration of code base

### ISSUE THREAD

**Issue by habu1010** [backwardsEric/hengband#16]
Hello, thank you for your continuous collaboration in Hengband development..

We are planning to migrate the Hengband code base to C++. With this branch of [the pull request](https://github.com/hengband/hengband/pull/422), C++ support is complete for the Windows and Linux/X11 versions.

However, there is no one in the development team who has the environment to build the Mac App version, and we are relying on you to release the Mac App version. Could you please check if the Mac App version can support the migration of the code base to C++?

**Comment by backwardsEric** [comment]
A quick hack to compile the Mac-specific code as Objective-C++ rather than Objective-C seemed to handle any issues of compatibility with Hengband's C++ header files or linking with its .o files.  The resulting executable ran and could start the character generation process.  I'll have to do a bit more testing to see if there's anything that's glaringly wrong with the C++ version.

The changes are in this branch of my fork, https://github.com/backwardsEric/hengband/tree/macos-develop-test-cpp .  All of the change were either in the Mac-specific source files or in the portions of configure.ac or src/Makefile.am that are specific to the Mac.  So far there's no additional changes that would need to be ported to the code that's in your feature/c++nize branch.

The results of the compilation test for the Mac are here, https://github.com/backwardsEric/hengband/actions/runs/626596977 , and the ones for Linux are here, https://github.com/backwardsEric/hengband/actions/runs/626596978 .

**Comment by habu1010** [comment]
Thanks for the confirmation.
I'm glad to hear that the Mac App version of the build looks fine.
I'll try to merge the C++ migration branch soon.

If there seems to be no problem, please close this Issue.

**Comment by backwardsEric** [comment]
I merged the C++ changes from Hengband's develop branch into the macos-develop branch of my fork and will close this as you suggested.
