### ISSUE TITLE
[Question] Latest Apple Clang

### ISSUE THREAD

**Issue by Hourier** [backwardsEric/hengband#37]
Hi,

As Ubuntu 24.04 is released, we Hengband dev team  started to plan to upgrade Clang to v18.
The day to change will be August or September.
(If some problem is found, it will be delayed to October or later.)

For the preparation, I'd like to know what the latest version of Apple Clang is.
Because Clang/Apple Clang has a tendency of slow development such as std::view.
Would you please tell us the info above?

Ref. Cmmpiler support list
(Apple Clang v16 or later seems not to be here...)
https://en.cppreference.com/w/cpp/compiler_support

**Comment by backwardsEric** [comment]
In case you did not know, Apple now puts information about support for C++ features on https://developer.apple.com/xcode/cpp/ .  According to https://en.wikipedia.org/wiki/Xcode (since I am still running macOS 12.7.4 and Xcode 14.2 with clang 14 locally), the latest released version of Xcode (15.3) uses clang 15.

**Comment by Hourier** [comment]
Thank you so much!
My question is resolved, so I close this case.
When we upgrade Clang in GitHub Actions to v15, we'll inform you.

Notes: Currently, I'm trying to change versions of GCC and Clang to latest versions.
https://github.com/hengband/hengband/pull/3931
